### ISSUE TITLE
Calendar date bug [Bug]

### ISSUE THREAD

**Issue by Skroas** [Julexar/calendar-dnd#25]
The calender for Greyhawk, modern day, and Tal'dorei keep changing the date whenever an action is done within the calender. This generally happens once you change the month.

![Screenshot 2024-04-19 at 11-02-53 Wildemount Roll20](https://github.com/Julexar/Calendar-DND/assets/166528144/a4850558-41ba-46ee-bdcf-b6a8fc411a9a)

**Comment by Julexar** [comment]
@Skroas The "Calendar-DND" Script is no longer supported. Please make sure to checkout https://github.com/Julexar/Faerun-Calendar and https://github.com/Multi-World-Calendar
